# Generated by Django 3.1.3 on 2020-11-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_name', models.CharField(max_length=200, unique=True)),
                ('matrix_value', models.CharField(max_length=200)),
            ],
        ),
    ]
