# Generated by Django 3.1.3 on 2020-11-29 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrix',
            name='matrix_value',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='MatrixGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_summary', models.CharField(max_length=200)),
                ('matrix_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='personal.matrix', verbose_name='Matrix')),
            ],
        ),
    ]
