# Generated by Django 3.1.3 on 2020-11-29 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20201129_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrixgroup',
            name='matrix_name',
        ),
        migrations.AddField(
            model_name='matrix',
            name='matrix_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='personal.matrixgroup', verbose_name='Category'),
        ),
    ]
