# Generated by Django 3.1.3 on 2020-12-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20201130_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrix',
            name='dimension',
            field=models.IntegerField(default=0),
        ),
    ]
