# Generated by Django 3.1.3 on 2020-12-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_matrix_dimension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixgroup',
            name='category_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
