# Generated by Django 3.1.3 on 2020-12-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_auto_20201203_2026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatrixGroup',
            new_name='Category',
        ),
    ]
