# Generated by Django 3.1.3 on 2020-12-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_auto_20201209_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_summary',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200, unique=True)),
                ('group_summary', models.CharField(default='', max_length=200)),
                ('matrices', models.ManyToManyField(to='personal.Matrix')),
            ],
            options={
                'ordering': ['group_name'],
            },
        ),
    ]
