# Generated by Django 3.1.3 on 2020-12-09 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_auto_20201209_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matrix',
            options={'ordering': ['matrix_name'], 'verbose_name': 'Matrix List'},
        ),
        migrations.AlterModelTable(
            name='matrix',
            table='matrix',
        ),
    ]
