# Generated by Django 3.1.3 on 2020-12-09 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_auto_20201209_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name'], 'verbose_name': 'Image Category', 'verbose_name_plural': 'Image Categories'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['group_name'], 'verbose_name': 'Image Group', 'verbose_name_plural': 'Image Groups'},
        ),
        migrations.AlterModelOptions(
            name='matrix',
            options={'ordering': ['matrix_name'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='image_category',
        ),
        migrations.AlterModelTable(
            name='group',
            table='image_group',
        ),
        migrations.AlterModelTable(
            name='matrix',
            table='image',
        ),
    ]
