# Generated by Django 3.1.3 on 2020-12-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_auto_20201209_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_summary',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_summary',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
