# Generated by Django 3.1.3 on 2020-12-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_auto_20201217_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='matrices',
            field=models.ManyToManyField(blank=True, to='personal.Matrix'),
        ),
        migrations.AlterField(
            model_name='group',
            name='matrices',
            field=models.ManyToManyField(blank=True, to='personal.Matrix'),
        ),
    ]
